services:
    galixte.moveaddfilesbutton.listener:
        class: galixte\moveaddfilesbutton\event\main_listener
        arguments:
            - '@user'
        tags:
            - { name: event.listener }